TXT_WITH_RECEPIENT_FOR_RANDOM_SENDING = 'etherscan_adresses.txt'

TXT_WITH_PRIVATE_KEYS = 'private_keys.txt'

REPORT_TABLE_NAME = 'report_table.csv'

NUMBER_OF_TRANSACTIONS = 10

NUMBER_OF_VARIATIONS_BETWEEN_SENDING_AMOUNT = 50

MIN_TIMESLEEP_BETWEEN_TRANSACTIONS = 18

MAX_TIMESLEEP_BETWEEN_TRANSACTIONS = 45

NUMBER_OF_MULTIPROCESSINGS = 2

MIN_TIMESLEEP_BETWEEN_MULTIPROCESSING = 10

MAX_TIMESLEEP_BETWEEN_MULTIPROCESSING = 20



